### ISSUE TITLE
Linked a google ical public url with an empty calendar and it crashed my humhub

### ISSUE THREAD

**Issue by danielrodd** [humhub-contrib/humhub-modules-external-calendar#3]
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'recurrence_until' in 'where clause'
The SQL being executed was: SELECT `external_calendar_entry`.* FROM `external_calendar_entry` LEFT JOIN `content` ON `external_calendar_entry`.`id` = `content`.`object_id` LEFT JOIN `contentcontainer` ON `content`.`contentcontainer_id` = `contentcontainer`.`id` LEFT JOIN `user` ON `content`.`created_by` = `user`.`id` LEFT JOIN `space` ON contentcontainer.pk=space.id AND contentcontainer.class='humhub\\modules\\space\\models\\Space' LEFT JOIN `user` `cuser` ON contentcontainer.pk=cuser.id AND contentcontainer.class='humhub\\modules\\user\\models\\User' LEFT JOIN `space_membership` ON contentcontainer.pk=space_membership.space_id AND contentcontainer.class='humhub\\modules\\space\\models\\Space' AND space_membership.user_id=1 LEFT JOIN `user_friendship` `cff` ON cuser.id=cff.user_id AND cff.friend_user_id=1 WHERE (((`start_datetime` >= '2020-01-25 10:45:27') AND (`start_datetime` <= '2020-02-25 10:45:27')) OR ((`end_datetime` >= '2020-01-25 10:45:27') AND (`end_datetime` <= '2020-02-25 10:45:27')) OR ((external_calendar_entry.rrule IS NOT NULL) AND (external_calendar_entry.parent_event_id IS NULL) AND ((recurrence_until IS NULL) OR (`recurrence_until` >= '2020-01-25 10:45:27')))) AND ((`contentcontainer`.`pk`=1) AND (`contentcontainer`.`class`='humhub\\modules\\space\\models\\Space')) AND (space.id IS NOT NULL AND ( (space_membership.status=3) OR (content.visibility=1 AND space.visibility != 0)) OR cuser.id IS NOT NULL AND ( (content.visibility = 1) OR (content.visibility = 0 AND content.contentcontainer_id=1) OR (content.visibility = 0 AND cff.id IS NOT NULL))OR content.created_by=1) AND (external_calendar_entry.parent_event_id IS NULL) AND (`content`.`object_model`='humhub\\modules\\external_calendar\\models\\ExternalCalendarEntry') AND (`content`.`object_model`='humhub\\modules\\external_calendar\\models\\ExternalCalendarEntry') ORDER BY `start_datetime` LIMIT 5

Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'recurrence_until' in 'where clause'
)

↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'recurrence_until' in 'where clause'

in /home3/danielrodd/public_html/app/protected/vendor/yiisoft/yii2/db/Command.php at line 1290

**Comment by buddh4** [comment]
Probably related to https://github.com/humhub-contrib/humhub-modules-external-calendar/issues/2
