### ISSUE TITLE
External calendar creation fails

### ISSUE THREAD

**Issue by verement** [humhub-contrib/humhub-modules-external-calendar#5]
When I attempt to add an external calendar, after clicking “Save” a new page briefly shows a notice at the bottom that says “Calendar successfully created!” but the top of the page shows an error message (“Oooops... It looks like you may have taken the wrong turn”): “Missing required parameters: id”.

There is no log message in the HumHub logs, and the external calendar does not in fact appear to be created.

HumHub version: 1.5.1
External Calendar version: 1.1.8

**Comment by verement** [comment]
After some additional diagnosis, it appears the problem occurs when data validation of the new external calendar fails.

`ExternalCalendar` has a surprising maximum `title` length of 15 characters. There is no check at `ICalSync.php:90` to see whether the call to save the calendar model fails.

**Comment by MasterMindNET** [comment]
I believe it was fixed before (by @buddh4), I have also added some validation if something is wrong.
https://github.com/humhub-contrib/humhub-modules-external-calendar/pull/16

**Comment by buddh4** [comment]
Yes is fixed and max title length was increased
